import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/navbar";

export const metadata: Metadata = {
  title: "Personal Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        {children}
        <Header></Header>
      </body>
    </html>
  );
}
